config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'reports#index'
  resources :users, only: [:show]
  resources :reports do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_dat.rb
class EventDay < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' }, { id: 2, name: 'キュン：個握 4月7日（日）大阪：大阪ATCホール' }, 
    { id: 3, name: 'キュン：全握 4月30日（火・祝）千葉：幕張メッセ' },{ id: 4, name: 'キュン：個握 5月6日（月・祝）千葉：幕張メッセ' }, 
    { id: 5, name: 'キュン：全握 5月12日（日）愛知：ポートメッセなごや' }, { id: 6, name: 'キュン：個握 6月8日（土）千葉：幕張メッセ' },
    { id: 7, name: 'キュン：全握 6月22日（土）京都：京都パルスプラザ' }, { id: 8, name: 'キュン：個握 6月30日（日）東京：東京ビッグサイト' }, 
    { id: 9, name: 'キュン：個握 7月21日（日）東京：東京流通センター' }, { id: 10, name: 'キュン：個握 8月11日（日）愛知：吹上ホール' }, 
    { id: 11, name: 'ドレミ：全握 8月17日(土)京都：京都パルスプラザ' }, { id: 12, name: 'ドレミ：個握 8月24日(土)神奈川：パシフィコ横浜' },
    { id: 13, name: 'ドレミ：個握 8月31日(土)神奈川：パシフィコ横浜' }, { id: 14, name: 'ドレミ：個握 9月14日(土)愛知：Aichi Sky Expo' }, 
    { id: 15, name: 'ドレミ：全握 9月16日(月・祝)千葉：幕張メッセ' }, { id: 16, name: 'ドレミ：全握 9月22日(日)愛知：Aichi Sky Expo' }, 
    { id: 17, name: 'ドレミ：個握 9月29日(日)京都：京都パルスプラザ' }, { id: 18, name: 'ドレミ：個握 10月13日(日)神奈川：パシフィコ横浜' },
    { id: 19, name: 'ドレミ：個握 10月22日(火・祝)東京：東京流通センター' }, { id: 20, name: 'こん好き：全握 10月19日（土）千葉・幕張メッセ' }, 
    { id: 21, name: 'こん好き：全握 11月3日（日）京都・京都パルスプラザ' }, { id: 22, name: 'こん好き：個握 11月24日（日）神奈川・パシフィコ横浜' }, 
    { id: 23, name: 'こん好き：全握 12月15日（日）愛知・Aichi sky expo（愛知県国際展示場）' }, { id: 24, name: 'こん好き：個握 1月18日（土）愛知・ポートメッセなごや' },
    { id: 25, name: 'こん好き：個握 1月19日（日）京都・パルスプラザ' }, { id: 26, name: 'こん好き：個握 2月2日（日）東京・東京ビッグクサイト' },
    { id: 27, name: 'ミートアンドグリート' } 
  ]
end

app/models/event_day.rb
class EventDay < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' }, { id: 2, name: 'キュン：個握 4月7日（日）大阪：大阪ATCホール' }, 
    { id: 3, name: 'キュン：全握 4月30日（火・祝）千葉：幕張メッセ' },{ id: 4, name: 'キュン：個握 5月6日（月・祝）千葉：幕張メッセ' }, 
    { id: 5, name: 'キュン：全握 5月12日（日）愛知：ポートメッセなごや' }, { id: 6, name: 'キュン：個握 6月8日（土）千葉：幕張メッセ' },
    { id: 7, name: 'キュン：全握 6月22日（土）京都：京都パルスプラザ' }, { id: 8, name: 'キュン：個握 6月30日（日）東京：東京ビッグサイト' }, 
    { id: 9, name: 'キュン：個握 7月21日（日）東京：東京流通センター' }, { id: 10, name: 'キュン：個握 8月11日（日）愛知：吹上ホール' }, 
    { id: 11, name: 'ドレミ：全握 8月17日(土)京都：京都パルスプラザ' }, { id: 12, name: 'ドレミ：個握 8月24日(土)神奈川：パシフィコ横浜' },
    { id: 13, name: 'ドレミ：個握 8月31日(土)神奈川：パシフィコ横浜' }, { id: 14, name: 'ドレミ：個握 9月14日(土)愛知：Aichi Sky Expo' }, 
    { id: 15, name: 'ドレミ：全握 9月16日(月・祝)千葉：幕張メッセ' }, { id: 16, name: 'ドレミ：全握 9月22日(日)愛知：Aichi Sky Expo' }, 
    { id: 17, name: 'ドレミ：個握 9月29日(日)京都：京都パルスプラザ' }, { id: 18, name: 'ドレミ：個握 10月13日(日)神奈川：パシフィコ横浜' },
    { id: 19, name: 'ドレミ：個握 10月22日(火・祝)東京：東京流通センター' }, { id: 20, name: 'こん好き：全握 10月19日（土）千葉・幕張メッセ' }, 
    { id: 21, name: 'こん好き：全握 11月3日（日）京都・京都パルスプラザ' }, { id: 22, name: 'こん好き：個握 11月24日（日）神奈川・パシフィコ横浜' }, 
    { id: 23, name: 'こん好き：全握 12月15日（日）愛知・Aichi sky expo（愛知県国際展示場）' }, { id: 24, name: 'こん好き：個握 1月18日（土）愛知・ポートメッセなごや' },
    { id: 25, name: 'こん好き：個握 1月19日（日）京都・パルスプラザ' }, { id: 26, name: 'こん好き：個握 2月2日（日）東京・東京ビッグクサイト' },
    { id: 27, name: 'ミートアンドグリート' } 
  ]
end

app/models/hope.rb
class Hope < ActiveHash::Base
  self.data = [
    { id: 1, name: '実レポ' }, { id: 2, name: '虚レポ' }
  ]
end

app/models/member_name.rb
class MemberName < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' }, { id: 2, name: '潮 紗理菜' }, { id: 3, name: '影山 優佳' },
    { id: 4, name: '加藤 史帆' }, { id: 5, name: '齊藤 京子' }, { id: 6, name: '佐々木 久美' },
    { id: 7, name: '佐々木 美玲' }, { id: 8, name: '高瀬 愛奈' }, { id: 9, name: '高本 彩花' },
    { id: 10, name: '東村 芽依' }, { id: 11, name: '金村 美玖' }, { id: 12, name: '河田 陽菜' },
    { id: 13, name: '小坂 菜緒' }, { id: 14, name: '富田 鈴花' }, { id: 15, name: '丹生 明里' },
    { id: 16, name: '濱岸 ひより' }, { id: 17, name: '松田 好花' }, { id: 18, name: '宮田 愛萌' },
    { id: 19, name: '渡邉 美穂' }, { id: 20, name: '上村 ひなの' }, { id: 21, name: '髙橋 未来虹' },
    { id: 22, name: '森本 茉莉' }, { id: 23, name: '山口 陽世' }, { id: 24, name: '井口眞緒' },
    { id: 25, name: '柿崎芽実' }, { id: 26, name: '長濱ねる' }
  ]
end

app/models/order.rb
class Order < ActiveHash::Base
  self.data = [
    { id: 1, name: '1' }, { id: 2, name: '2' }, { id: 3, name: '3' },
    { id: 4, name: '4' }, { id: 5, name: '5' }, { id: 6, name: '6' },
    { id: 7, name: '7' }, { id: 8, name: '8' }, { id: 9, name: '9' },
    { id: 10, name: '10' }, { id: 11, name: '11' }, { id: 12, name: '12' },
    { id: 13, name: '13' }, { id: 14, name: '14' }, { id: 15, name: '15' },
    { id: 16, name: '16' }, { id: 17, name: '17' }, { id: 18, name: '18' },
    { id: 19, name: '19' }, { id: 20, name: '20' }
  ]
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :EventDay
    belongs_to_active_hash :Hope
    belongs_to_active_hash :MemberName

  with_options presence: true do
    validates :hope_id, numericality: { less_than: 2 }
    validates :event_day_id, inclusion: { in: 2..27 }
    validates :member_name_id, inclusion: { in: 2..25 }
    validates :sheets, numericality: {only_integer: true}
    validates :text
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
    def basic_auth
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
      end
    end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @reports = Report.all.order("id  DESC").page(params[:page]).per(12)
  end
  
  def show
    @report = Report.find(params[:id])
  end

  def new
    report = Report.new
  end

  def create
    @report = Report.new(report_params)
    if @report.valid?
      @report.save
      redirect_to root_path
    else 
      render 'new'
    end
  end

  def edit
    @report = Report.find(params[:id])
    redirect_to root_path if current_user.id != @report.id
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(report_update_params)
      redirect_to report_path(@report)
    else
      render "edit"
    end
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    redirect_to root_path
  end

  def search
    @reports = Report.where(member_name_id: params[:member_name_id])
  end

  private
  
  def report_params
    params.permit(:hope_id, :event_day_id, :member_name_id, :sheets, :text).merge(user_id: current_user.id)
  end

  def report_update_params
    params.require(:report).permit(:hope_id, :event_day_id, :member_name_id, :sheets, :text).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @reports = Report.where(user_id: @user).page(params[:page]).per(12)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/edit.html.erb
<%= render 'shared/header' %>
<body class="text-center">
  <div class="pt-5">
    <div class="container shadow p-3 bg-white rounded" style="width: 50%;">
    <h1 class="h3 m-3 font-weight-normal pt-4">投稿編集</h1>
    <%= form_with model: @report, url: report_path, local: true do |f| %>
      <div class="card p4" style="width: 100%;">
        
        <div class="input-group mb-3">
          <div class="input-group mb-2 ml-3  d-flex align-items-center">
            レポの種類
          </div>
          <div class="input-group mb-2 ml-3 d-flex align-items-center">
            <%= f.collection_select(:hope_id, Hope.all, :id, :name, {})  %>
          </div>
        </div>

        <div class="input-group mb-3">
          <div class="input-group mb-2 ml-3  d-flex align-items-center">
            日程
          </div>
          <div class="input-group mb-2 ml-3 d-flex align-items-center">
            <%= f.collection_select(:event_day_id, EventDay.all, :id, :name, {})  %>
          </div>
        </div>

         <div class="input-group mb-3">
          <div class="input-group mb-2 ml-3  d-flex align-items-center">
            メンバー
          </div>
          <div class="input-group mb-2 ml-3 d-flex align-items-center">
            <%= f.collection_select(:member_name_id, MemberName.all, :id, :name, {})  %>
          </div>
        </div>

        <div class="input-group mb-3">
          <div class="input-group mb-2 ml-3  d-flex align-items-center">
            枚数
          </div>
          <div class="col align-self-center mb-2">
            <%= f.text_field :sheets, autofocus: true, autocomplete: "sheets", class:"form-control", placeholder: ""  %>
          </div>
        </div>

        <div class="input-group mb-3">
          <div class="input-group mb-2 ml-3  d-flex align-items-center">
            会話内容
          </div>
          <div class="col align-self-center mb-2">
            <%= f.text_area :text, autofocus: true, autocomplete: "text", class:"form-control", placeholder: ""  %>
          </div>
        </div>

        <div class="actions">
          <%= f.submit "編集する", class: "mb-3 btn btn-primary btn-lg"%>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</body>

app/views/reports/index.html.erb
<%= render 'shared/header' %>

<%# アイキャッチ画像 %>
    <%= image_tag "handshare_top.jpg", class:"d-block w-100" %>

<%# 投稿検索フォーム %>
  <div class="m-3 text-center">
    <h3 class="mb-3">投稿検索</h3>
    <%= form_with(url: search_reports_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.collection_select(:member_name_id, MemberName.all, :id, :name, {}) %>
      <%= f.submit "検索", class: "search-btn" %>
    <% end %>
  </div>

<div class="m-3 text-center mb-5">
    <h3 class="mb-5 mt-5 text-center">最新レポ一覧</h3>
    <div class="container">
      <div class="row justify-content-center">
        <div class="card-deck">
          <% @reports.each do |report| %>
            <div class="col-xs-10 col-sm-6 col-md-4 mb-4">
              <div class="card-deck">
                <div class="card" style="width: 250px;">
                  <div class="border border-success" >
                    <div class="card-body text-center">
                      <p class="card-text">レポの種類:<%=report.Hope.name %></p>
                      <p class="card-text">枚数:<%=report.sheets %></p>
                      <p class="card-text">メンバー:<%=report.MemberName.name%></p>
                      <%= link_to '詳細を表示する', report_path(report), class:'btn btn-primary' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="d-flex justify-content-center">
        <%= paginate @reports %>
      </div>
    </div>
</div> 

app/views/reports/new.html.erb
<%= render 'shared/header' %>
<body class="text-center">
  <div class="row justify-content-around">
    <div class="col-xs-10  col-md-8 shadow p-3 bg-white rounded">
    <h1 class="h3 m-3 font-weight-normal pt-4">新規投稿</h1>
    <%= form_with model: @report, url: reports_path, local: true do |f| %>
      <div class="card p4" style="width: 100%;">
        
        <div class="input-group mb-3">
          <div class="input-group mb-2 ml-3  d-flex align-items-center">
            レポの種類
          </div>
          <div class="input-group mb-2 ml-3 d-flex align-items-center">
            <%= f.collection_select(:hope_id, Hope.all, :id, :name, {})  %>
          </div>
        </div>

        <div class="input-group mb-3">
          <div class="input-group mb-2 ml-3  d-flex align-items-center">
            日程
          </div>
          <div class="input-group mb-2 ml-3 d-flex align-items-center">
            <%= f.collection_select(:event_day_id, EventDay.all, :id, :name, {})  %>
          </div>
        </div>

         <div class="input-group mb-3">
          <div class="input-group mb-2 ml-3  d-flex align-items-center">
            メンバー
          </div>
          <div class="input-group mb-2 ml-3 d-flex align-items-center">
            <%= f.collection_select(:member_name_id, MemberName.all, :id, :name, {})  %>
          </div>
        </div>

        <div class="input-group mb-3">
          <div class="input-group mb-2 ml-3  d-flex align-items-center">
            枚数
          </div>
          <div class="col align-self-center mb-2">
            <%= f.text_field :sheets, autofocus: true, autocomplete: "sheets", class:"form-control", placeholder: ""  %>
          </div>
        </div>

        <div class="input-group mb-3">
          <div class="input-group mb-2 ml-3  d-flex align-items-center">
            会話内容
          </div>
          <div class="col align-self-center mb-2">
            <%= f.text_area :text, autofocus: true, autocomplete: "text", class:"form-control", placeholder: "", size: "20x10"%>
          </div>
        </div>

        <div class="actions">
          <%= f.submit "投稿する", class: "mb-3 btn btn-primary btn-lg"%>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</body>

app/views/reports/search.html.erb
<%= render 'shared/header' %>

<%# アイキャッチ画像 %>
    <%= image_tag "handshare_top.jpg", class:"d-block w-100" %>

<%# 投稿検索フォーム %>
  <div class="m-3 text-center">
    <h3 class="mb-3">投稿検索</h3>
    <%= form_with(url: search_reports_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.collection_select(:member_name_id, MemberName.all, :id, :name, {}) %>
      <%= f.submit "検索", class: "search-btn" %>
    <% end %>
  </div>

<div class="m-3 text-center">
    <h3 class="mb-3 mt-5 text-center">検索結果一覧</h3>
    <div class="d-flex justify-content-center">
      <% @reports.each do |report| %>
        <div class="col-md-2 mb-5">
          <div class="border border-success" >
            <div class="card-body text-center">
              <p class="card-text">レポの種類:<%=report.Hope.name %></p>
              <p class="card-text">枚数:<%=report.sheets %></p>
              <p class="card-text">メンバー:<%=report.MemberName.name%></p>
              <%= link_to '詳細を表示する', report_path(report), class:'btn btn-primary' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div> 

app/views/reports/show.html.erb
<%= render 'shared/header' %>
<body class="text-center">

  <div class="row justify-content-around">
    <div class="col-xs-10  col-md-8 shadow p-3 bg-white rounded">
      <h1 class="h3 m-2 font-weight-normal pt-4">投稿詳細</h1>
        <%if current_user.id == @report.user.id %>
          <%= link_to "編集",  edit_report_path(@report) %>
        <% end %>
        <ul class="list-group list-group-flush text-left">
          <li class="list-group-item p-3">投稿者：<%=link_to @report.user.nickname, user_path(@report.user)%></li>
          </li>
          <li class="list-group-item p-3">レポの種類：<%= @report.Hope.name %></li>
          <li class="list-group-item p-3">日程：<%= @report.EventDay.name %></li>
          <li class="list-group-item p-3">枚数：<%= @report.sheets %></li>
          <li class="list-group-item p-3">メンバー：<%= @report.MemberName.name%></li> 
          <li class="list-group-item p-3">内容：<%= @report.text%></li>
        </ul>
        <%if current_user.id == @report.user.id %>
          <%= link_to "削除",  report_path(@report), method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/shared/_header.html.erb
<header>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
      <%= link_to 'Handshare', root_path, class:'my-0 mr-md-auto font-weight-normal btn btn-outline-secondary btn-lg' %>
    <nav class="my-2 my-md-0 mr-md-3">
      <% if user_signed_in? %>
        こんにちは <%=current_user.nickname %>さん
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'ml-2 p-2 text-primary btn btn-outline-primary' %>
        <%= link_to '新規投稿', new_report_path, class:'ml-2 p-2 text-primary btn btn-outline-primary' %>
      <% else %>
        <%= link_to 'ユーザー登録', new_user_registration_path, class:'ml-2 p-2 text-primary btn btn-outline-primary' %>
        <%= link_to 'ログイン', new_user_session_path, class:'ml-2 p-2 text-primary btn btn-outline-primary ' %>
      <% end %>
    </nav>
  </div>  
</header>

app/views/users/show.html.erb
<%= render 'shared/header' %>

<div class="m-3 text-center mb-5">
  <h3 class="mb-3 mt-5 text-center"><%= @user.nickname %>さんのレポ一覧</h3>
  <div class="container">
    <div class="row justify-content-center">
      <div class="card-deck">
        <% @reports.each do |report| %>
          <div class="col-xs-10 col-sm-6 col-md-4 mb-4">
            <div class="card-deck">
              <div class="card" style="width: 250px;">
                <div class="border border-success" >
                  <div class="card-body text-center">
                    <p class="card-text">レポの種類:<%=report.Hope.name %></p>
                    <p class="card-text">枚数:<%=report.sheets %></p>
                    <p class="card-text">メンバー:<%=report.MemberName.name%></p>
                    <%= link_to '詳細を表示する', report_path(report), class:'btn btn-primary' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center">
        <%= paginate @reports %>
      </div>
</div> 